// HAND-OWNED (quick-log). Not generated by Bubblewrap.
package io.github.palo007.twa.quicklog

import android.content.Context
import android.content.SharedPreferences
import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import com.dropbox.core.DbxRequestConfig
import com.dropbox.core.android.Auth
import com.dropbox.core.oauth.DbxCredential
import com.dropbox.core.v2.DbxClientV2
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Separate Dropbox login for the Android part (plan D7). Same app key as the
 * PWA (Opti sync.js DBX_APP_KEY), so both see the same app folder.
 * The PWA's token lives in Chrome storage; the phone cannot read it.
 */
object DropboxAuth {
    const val APP_KEY = "9bmdhb7j1b5nuke"

    private const val KEY_CRED = "dbx_cred"
    private const val KEY_LOGIN_PENDING = "dbx_login_pending"
    private const val KEY_AUTH_BROKEN = "dbx_auth_broken"

    val requestConfig: DbxRequestConfig by lazy {
        DbxRequestConfig.newBuilder("questa-android/1").build()
    }

    @JvmStatic
    fun prefs(ctx: Context): SharedPreferences =
        ctx.applicationContext.getSharedPreferences("questa_quicklog", Context.MODE_PRIVATE)

    fun startLogin(ctx: Context) {
        prefs(ctx).edit().putBoolean(KEY_LOGIN_PENDING, true).apply()
        // No explicit scopes: the token gets what the App Console grants, same as the PWA.
        Auth.startOAuth2PKCE(ctx, APP_KEY, requestConfig)
    }

    /**
     * Call from onResume. Auth.getDbxCredential() keeps returning the last result, so we
     * only take it while our own login is pending; otherwise a later resume would bring
     * back a credential the user already disconnected.
     */
    fun captureLoginResult(ctx: Context): Boolean {
        val p = prefs(ctx)
        if (!p.getBoolean(KEY_LOGIN_PENDING, false)) return false
        val cred = Auth.getDbxCredential() ?: return false
        p.edit()
            .putString(KEY_CRED, CredentialCrypto.seal(DbxCredential.Writer.writeToString(cred)))
            .putBoolean(KEY_LOGIN_PENDING, false)
            .putBoolean(KEY_AUTH_BROKEN, false)
            .apply()
        return true
    }

    fun credential(ctx: Context): DbxCredential? {
        val sealed = prefs(ctx).getString(KEY_CRED, null) ?: return null
        val json = CredentialCrypto.open(sealed) ?: return null
        return try { DbxCredential.Reader.readFully(json) } catch (e: Exception) { null }
    }

    @JvmStatic
    fun isConnected(ctx: Context): Boolean = credential(ctx) != null

    /** The token refreshes itself in memory; the refresh token is long-lived. */
    fun client(ctx: Context): DbxClientV2? = credential(ctx)?.let { DbxClientV2(requestConfig, it) }

    fun markAuthBroken(ctx: Context) {
        prefs(ctx).edit().putBoolean(KEY_AUTH_BROKEN, true).apply()
    }

    fun isAuthBroken(ctx: Context): Boolean = prefs(ctx).getBoolean(KEY_AUTH_BROKEN, false)

    /** Local sign-out. Queued taps stay queued and upload after the next connect. */
    fun disconnect(ctx: Context) {
        val c = client(ctx)
        prefs(ctx).edit()
            .remove(KEY_CRED)
            .putBoolean(KEY_LOGIN_PENDING, false)
            .putBoolean(KEY_AUTH_BROKEN, false)
            .apply()
        if (c != null) Thread { try { c.auth().tokenRevoke() } catch (e: Exception) { } }.start()
    }
}

/**
 * Seals the credential JSON with an AES-GCM key in the Android Keystore (API 23+).
 * androidx.security-crypto is deprecated upstream, so this uses the platform API directly.
 * API 21-22 have no Keystore AES: there the JSON stays in app-private prefs ("p0:").
 * After a backup restore to a new phone the key is gone, open() returns null and the
 * user simply connects again.
 */
internal object CredentialCrypto {
    private const val ALIAS = "questa_quicklog_cred"
    private const val TAG_BITS = 128

    fun seal(plain: String): String {
        if (Build.VERSION.SDK_INT < 23) return "p0:$plain"
        val c = Cipher.getInstance("AES/GCM/NoPadding")
        c.init(Cipher.ENCRYPT_MODE, key())
        val ct = c.doFinal(plain.toByteArray(Charsets.UTF_8))
        return "k1:" + b64(c.iv) + ":" + b64(ct)
    }

    fun open(sealed: String): String? = try {
        when {
            sealed.startsWith("p0:") -> sealed.substring(3)
            sealed.startsWith("k1:") && Build.VERSION.SDK_INT >= 23 -> {
                val parts = sealed.split(':')
                val c = Cipher.getInstance("AES/GCM/NoPadding")
                c.init(Cipher.DECRYPT_MODE, key(), GCMParameterSpec(TAG_BITS, unb64(parts[1])))
                String(c.doFinal(unb64(parts[2])), Charsets.UTF_8)
            }
            else -> null
        }
    } catch (e: Exception) {
        null
    }

    private fun key(): SecretKey {
        val ks = KeyStore.getInstance("AndroidKeyStore").apply { load(null) }
        (ks.getKey(ALIAS, null) as? SecretKey)?.let { return it }
        val g = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, "AndroidKeyStore")
        g.init(
            KeyGenParameterSpec.Builder(ALIAS, KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT)
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .build()
        )
        return g.generateKey()
    }

    private fun b64(b: ByteArray) = Base64.encodeToString(b, Base64.NO_WRAP)
    private fun unb64(s: String) = Base64.decode(s, Base64.NO_WRAP)
}
