// HAND-OWNED (quick-log). Not generated by Bubblewrap.
package io.github.palo007.twa.quicklog

import org.json.JSONObject

data class Habit(val id: String, val title: String, val quickLog: Boolean, val dirs: List<Int> = emptyList())

/** One shortcut-worthy (habit, direction) pair, in the order shortcuts should be published. */
data class ShortcutItem(val habit: Habit, val dir: Int)

/**
 * Reads /inbox-meta/habits.json, written by the PWA after a good sync:
 * {"v":1,"updatedAt":<ms>,"habits":[{"id","title","quickLog","dirs":[1,-1]}]}
 * Returns null when the file is not a v1 list, so a bad file never wipes the menu.
 */
fun parseHabitList(text: String): List<Habit>? {
    val o = try { JSONObject(text) } catch (e: Exception) { return null }
    if (o.optInt("v", 0) != 1) return null
    val arr = o.optJSONArray("habits") ?: return null
    val out = ArrayList<Habit>(arr.length())
    for (i in 0 until arr.length()) {
        val h = arr.optJSONObject(i) ?: continue
        val id = h.optString("id", "")
        if (id.isEmpty()) continue
        val title = h.optString("title", "").trim().ifEmpty { id }
        val quickLog = h.optBoolean("quickLog", false)
        val dirs = parseDirs(h.optJSONArray("dirs"), quickLog)
        out.add(Habit(id, title, quickLog, dirs))
    }
    return out
}

/**
 * Old files have no `dirs`: if `quickLog` is true, treat as [1]. Values other than 1/-1 are
 * dropped, and duplicates are removed, keeping first-seen order.
 */
private fun parseDirs(arr: org.json.JSONArray?, quickLog: Boolean): List<Int> {
    if (arr == null) return if (quickLog) listOf(1) else emptyList()
    val out = ArrayList<Int>()
    for (i in 0 until arr.length()) {
        val v = arr.opt(i)
        val n = (v as? Number)?.toInt()
        if ((n == 1 || n == -1) && n !in out) out.add(n)
    }
    return out
}

/**
 * The shortcut items to publish: for each habit in the web app's order, its resolved directions
 * (+1 before -1), skipping habits with no resolved dirs, deduped by habit id, capped at [cap]
 * ITEMS (a habit contributing two items counts as two toward the cap).
 */
fun pickShortcutItems(habits: List<Habit>, cap: Int): List<ShortcutItem> {
    if (cap <= 0) return emptyList()
    val seen = HashSet<String>()
    val out = ArrayList<ShortcutItem>()
    for (h in habits) {
        if (h.dirs.isEmpty()) continue
        if (!seen.add(h.id)) continue
        for (dir in listOf(1, -1)) {
            if (dir !in h.dirs) continue
            if (out.size >= cap) return out
            out.add(ShortcutItem(h, dir))
        }
    }
    return out
}
