// HAND-OWNED (quick-log). Not generated by Bubblewrap.
package io.github.palo007.twa.quicklog

import java.util.TimeZone
import java.util.UUID

/**
 * One headless quick-log tap. The JSON must match the web consumer
 * (Opti sync.js inboxParseRecord) exactly, or the PWA moves the file to
 * /inbox-rejected/. Frozen contract, v1:
 * {"v":1,"id":"<uuid>","kind":"habit","habitId":"<id>","dir":1,"ts":<ms>,"tzOffsetMin":<int>,"src":"android-shortcut"}
 */
data class InboxRecord(
    val id: String,
    val habitId: String,
    val dir: Int,
    val ts: Long,
    val tzOffsetMin: Int,
    val src: String = SRC,
) {
    init {
        require(ID_RE.matches(id)) { "bad id" }
        require(habitId.isNotEmpty()) { "empty habitId" }
        require(dir == 1 || dir == -1) { "bad dir" }
        require(ts > 0) { "bad ts" }
    }

    val fileName: String get() = "$id.json"

    /** Hand-built so numbers stay numbers and the output is unit-testable without org.json. */
    fun toJson(): String =
        "{\"v\":1,\"id\":${q(id)},\"kind\":\"habit\",\"habitId\":${q(habitId)}," +
            "\"dir\":$dir,\"ts\":$ts,\"tzOffsetMin\":$tzOffsetMin,\"src\":${q(src)}}"

    companion object {
        const val SRC = "android-shortcut"
        /** Same rule as the web side: file name `<id>.json`, id 8..64 of [A-Za-z0-9-]. */
        val ID_RE = Regex("^[A-Za-z0-9-]{8,64}$")

        /**
         * A new tap. `tzOffsetMin` uses the JavaScript getTimezoneOffset() sign
         * (UTC minus local: CEST gives -120), so both sides mean the same thing.
         */
        fun create(habitId: String, nowMs: Long, tz: TimeZone, dir: Int = 1): InboxRecord =
            InboxRecord(
                id = UUID.randomUUID().toString(),
                habitId = habitId,
                dir = dir,
                ts = nowMs,
                tzOffsetMin = -tz.getOffset(nowMs) / 60000,
            )

        internal fun q(s: String): String {
            val b = StringBuilder(s.length + 2).append('"')
            for (c in s) {
                when {
                    c == '"' -> b.append("\\\"")
                    c == '\\' -> b.append("\\\\")
                    c == '\n' -> b.append("\\n")
                    c == '\r' -> b.append("\\r")
                    c == '\t' -> b.append("\\t")
                    c < ' ' || c == ' ' || c == ' ' ->
                        b.append(String.format("\\u%04x", c.code))
                    else -> b.append(c)
                }
            }
            return b.append('"').toString()
        }
    }
}
