// HAND-OWNED (quick-log). Not generated by Bubblewrap.
package io.github.palo007.twa.quicklog

import android.content.Context
import androidx.work.BackoffPolicy
import androidx.work.Constraints
import androidx.work.ExistingWorkPolicy
import androidx.work.NetworkType
import androidx.work.OneTimeWorkRequest
import androidx.work.WorkManager
import androidx.work.Worker
import androidx.work.WorkerParameters
import com.dropbox.core.DbxException
import com.dropbox.core.InvalidAccessTokenException
import com.dropbox.core.v2.files.UploadErrorException
import com.dropbox.core.v2.files.WriteMode
import java.io.IOException
import java.util.concurrent.TimeUnit

/**
 * Uploads each queued tap to /inbox/<id>.json with mode "add" (never overwrite).
 * The local file is deleted only after Dropbox confirmed it. A name conflict means an
 * earlier run already uploaded it (reply lost): delete locally. A re-upload after the PWA
 * already consumed the file is harmless: the PWA skips a uid it has seen (plan D3).
 */
class InboxUploadWorker(ctx: Context, params: WorkerParameters) : Worker(ctx, params) {

    override fun doWork(): Result {
        val ctx = applicationContext
        // Not connected: keep the queue. Connecting enqueues this worker again.
        val client = DropboxAuth.client(ctx) ?: return Result.success()
        val store = InboxStore(ctx)
        var uploaded = 0
        var retry = false
        for (f in store.list()) {
            if (isStopped) return Result.retry()
            val id = f.name.removeSuffix(".json")
            if (!InboxRecord.ID_RE.matches(id)) continue
            try {
                f.inputStream().use { input ->
                    client.files().uploadBuilder("/inbox/$id.json")
                        .withMode(WriteMode.ADD)
                        .withAutorename(false)
                        .withMute(true)
                        .uploadAndFinish(input)
                }
                store.delete(f)
                uploaded++
            } catch (e: UploadErrorException) {
                val err = e.errorValue
                if (err.isPath && err.pathValue.reason.isConflict) {
                    store.delete(f)
                } else {
                    retry = true
                }
            } catch (e: InvalidAccessTokenException) {
                // Token revoked or expired for good: stop, keep every file, ask the user to reconnect.
                DropboxAuth.markAuthBroken(ctx)
                ShortcutPublisher.publish(ctx)
                return Result.failure()
            } catch (e: DbxException) {
                retry = true
            } catch (e: IOException) {
                retry = true
            }
        }
        if (uploaded > 0) {
            DropboxAuth.prefs(ctx).edit().putLong(KEY_LAST_UPLOAD, System.currentTimeMillis()).apply()
            ShortcutRefreshWorker.enqueueNow(ctx)
        }
        return if (retry) Result.retry() else Result.success()
    }

    companion object {
        const val KEY_LAST_UPLOAD = "last_upload_ms"
        private const val WORK_NAME = "questa-inbox-upload"

        /** APPEND_OR_REPLACE: a tap during a running upload still gets its own run after it. */
        fun enqueue(ctx: Context) {
            val req = OneTimeWorkRequest.Builder(InboxUploadWorker::class.java)
                .setConstraints(Constraints.Builder().setRequiredNetworkType(NetworkType.CONNECTED).build())
                .setBackoffCriteria(BackoffPolicy.EXPONENTIAL, 30, TimeUnit.SECONDS)
                .build()
            WorkManager.getInstance(ctx.applicationContext)
                .enqueueUniqueWork(WORK_NAME, ExistingWorkPolicy.APPEND_OR_REPLACE, req)
        }
    }
}
