// HAND-OWNED (quick-log). Not generated by Bubblewrap.
package io.github.palo007.twa.quicklog

import android.content.Context
import java.io.File
import java.io.IOException

/**
 * Local queue of taps not yet uploaded: one immutable file per tap in
 * filesDir/inbox/<id>.json. Survives reboot and app updates.
 */
class InboxStore(context: Context) {
    private val dir = File(context.filesDir, "inbox")

    @Throws(IOException::class)
    fun write(rec: InboxRecord) {
        if (!dir.isDirectory && !dir.mkdirs()) throw IOException("cannot create $dir")
        val tmp = File(dir, rec.fileName + ".tmp")
        tmp.writeText(rec.toJson(), Charsets.UTF_8)
        // rename is atomic on one file system: the uploader never sees a half-written file.
        if (!tmp.renameTo(File(dir, rec.fileName))) {
            tmp.delete()
            throw IOException("cannot store ${rec.fileName}")
        }
    }

    /** Oldest first, so the web side sees taps roughly in order. */
    fun list(): List<File> =
        (dir.listFiles { f -> f.isFile && f.name.endsWith(".json") } ?: emptyArray())
            .sortedBy { it.lastModified() }

    fun count(): Int = list().size

    fun delete(f: File) {
        f.delete()
    }
}
