// HAND-OWNED (quick-log). Not generated by Bubblewrap.
package io.github.palo007.twa.quicklog

import android.content.Context
import android.util.Log

/**
 * Called from Application.onCreate (one hand-added line). Runs on every process start,
 * so it must be cheap and must never break the TWA launch.
 */
object QuickLogBootstrap {
    @JvmStatic
    fun onAppStart(ctx: Context) {
        try {
            // First run before any Dropbox login: this puts "Connect Dropbox" in the menu.
            ShortcutPublisher.publish(ctx)
            if (DropboxAuth.isConnected(ctx)) {
                ShortcutRefreshWorker.ensurePeriodic(ctx)
                ReminderSyncWorker.enqueueNow(ctx)
                ReminderSyncWorker.ensurePeriodic(ctx)
            }
            // Re-arm from whatever we already have even if not connected (e.g. right after boot).
            ReminderScheduler.rearm(ctx)
            if (InboxStore(ctx).count() > 0) InboxUploadWorker.enqueue(ctx)
        } catch (t: Throwable) {
            Log.w("QuestaQuickLog", "bootstrap failed", t)
        }
    }
}
