// HAND-OWNED (quick-log). Not generated by Bubblewrap.
package io.github.palo007.twa.quicklog

import android.app.Activity
import android.os.Bundle
import android.widget.Toast
import java.util.TimeZone

/**
 * Target of a long-press habit item. No UI: queue the tap, show a toast, finish.
 * It never starts LauncherActivity, so the TWA does not open. The tap time is taken
 * here, so a log made offline keeps its real time.
 */
class QuickLogActivity : Activity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val habitId = intent?.getStringExtra(EXTRA_HABIT_ID)
        val title = intent?.getStringExtra(EXTRA_TITLE)?.takeIf { it.isNotBlank() } ?: "Habit"
        val dir = intent?.getIntExtra(EXTRA_DIR, 1)?.let { if (it == -1) -1 else 1 } ?: 1
        val msg = if (habitId.isNullOrEmpty()) {
            "Quick log: this item has no habit. Remove it and add it again."
        } else {
            try {
                InboxStore(this).write(InboxRecord.create(habitId, System.currentTimeMillis(), TimeZone.getDefault(), dir))
                InboxUploadWorker.enqueue(this)
                ShortcutRefreshWorker.ensurePeriodic(this)
                when {
                    !DropboxAuth.isConnected(this) -> "Logged. Connect Dropbox to sync."
                    DropboxAuth.isAuthBroken(this) -> "Logged. Reconnect Dropbox to sync."
                    dir == -1 -> "$title −1 logged ✓"
                    else -> "$title +1 logged ✓"
                }
            } catch (e: Exception) {
                "Could not save the log for $title"
            }
        }
        Toast.makeText(applicationContext, msg, Toast.LENGTH_SHORT).show()
        finish()
    }

    override fun finish() {
        super.finish()
        overridePendingTransition(0, 0)
    }

    companion object {
        const val ACTION = "io.github.palo007.twa.QUICK_LOG"
        const val EXTRA_HABIT_ID = "habitId"
        const val EXTRA_TITLE = "title"
        const val EXTRA_DIR = "dir"
    }
}
