// HAND-OWNED (quick-log). Not generated by Bubblewrap.
package io.github.palo007.twa.quicklog

import android.content.Context
import java.util.Calendar
import java.util.TimeZone

/**
 * Cross-process "was this exact slot just shown" check so the native alarm path
 * (`ReminderReceiver`) and the web-delegated notification path (`DelegationService`) do not both
 * post the same reminder. Prefs-backed (`DropboxAuth.prefs`) so it survives process death and is
 * visible from either side.
 *
 * Phase 1E: replaces the old title+3-minute window with a SLOT identity: `title|yyyy-MM-dd|HH:MM`
 * (phone local date/time). Native and web each get their own record (`markNative`/`markWeb`,
 * `nativeShown`/`webShown`) so either side can tell whether the OTHER side already covered a given
 * slot, without one side's write clobbering the other's. Only titles present in the stored
 * reminder list are ever tracked (enforced by the callers), so ad-hoc web notifications (e.g. the
 * "Questa Test" button) are never recorded or dropped.
 */
object ReminderDedupe {
    private const val PREFIX_NATIVE = "reminder_slot_native_"
    private const val PREFIX_WEB = "reminder_slot_web_"
    val PRUNE_AGE_MS = 2 * 24 * 60 * 60 * 1000L

    /** Pure: `title|yyyy-MM-dd|HH:MM`. Split out so it needs no Context to unit-test. */
    @JvmStatic
    fun buildSlotKey(title: String, dateStr: String, timeStr: String): String =
        "$title|$dateStr|$timeStr"

    /** Pure: phone-local "yyyy-MM-dd" for [nowMs] in [tz]. */
    @JvmStatic
    fun localDateString(nowMs: Long, tz: TimeZone): String {
        val cal = Calendar.getInstance(tz)
        cal.timeInMillis = nowMs
        return String.format(
            "%04d-%02d-%02d",
            cal.get(Calendar.YEAR),
            cal.get(Calendar.MONTH) + 1,
            cal.get(Calendar.DAY_OF_MONTH)
        )
    }

    /** Pure: zero-padded "HH:MM". */
    @JvmStatic
    fun timeString(hour: Int, minute: Int): String = String.format("%02d:%02d", hour, minute)

    /**
     * Pure: extracts "HH:MM" from a body that starts with `Missed at HH:MM - ...` (the web app's
     * missed-reminder format), or null if [body] does not match (an on-time reminder body).
     */
    @JvmStatic
    fun parseMissedTime(body: String?): String? {
        if (body == null) return null
        val m = MISSED_AT_RE.find(body) ?: return null
        return m.groupValues[1]
    }

    /**
     * Pure: the slot time(s) a web notification with this [body] could be covering, as "HH:MM"
     * (not yet joined with a title/date). A missed one names its own time; an on-time one does
     * not carry a time in the body, so both "now" and "now-1min" are offered as candidates to
     * absorb the gap between the native alarm firing and the web delegated notification arriving.
     */
    @JvmStatic
    fun candidateTimes(body: String?, nowMs: Long, tz: TimeZone): List<String> {
        val missed = parseMissedTime(body)
        if (missed != null) return listOf(missed)
        val cal = Calendar.getInstance(tz)
        cal.timeInMillis = nowMs
        val now = timeString(cal.get(Calendar.HOUR_OF_DAY), cal.get(Calendar.MINUTE))
        cal.add(Calendar.MINUTE, -1)
        val minusOne = timeString(cal.get(Calendar.HOUR_OF_DAY), cal.get(Calendar.MINUTE))
        return if (now == minusOne) listOf(now) else listOf(now, minusOne)
    }

    @JvmStatic
    @JvmOverloads
    fun markNative(ctx: Context, slot: String, nowMs: Long = System.currentTimeMillis()) {
        mark(ctx, PREFIX_NATIVE, slot, nowMs)
    }

    @JvmStatic
    @JvmOverloads
    fun markWeb(ctx: Context, slot: String, nowMs: Long = System.currentTimeMillis()) {
        mark(ctx, PREFIX_WEB, slot, nowMs)
    }

    @JvmStatic
    fun nativeShown(ctx: Context, slot: String): Boolean =
        DropboxAuth.prefs(ctx).contains(PREFIX_NATIVE + slot)

    @JvmStatic
    fun webShown(ctx: Context, slot: String): Boolean =
        DropboxAuth.prefs(ctx).contains(PREFIX_WEB + slot)

    private fun mark(ctx: Context, prefix: String, slot: String, nowMs: Long) {
        val p = DropboxAuth.prefs(ctx)
        val editor = p.edit()
        editor.putLong(prefix + slot, nowMs)
        pruneOld(p, editor, nowMs)
        editor.apply()
    }

    /** Removes any native/web slot record older than [PRUNE_AGE_MS], on every write. */
    private fun pruneOld(p: android.content.SharedPreferences, editor: android.content.SharedPreferences.Editor, nowMs: Long) {
        for ((k, v) in p.all) {
            if ((k.startsWith(PREFIX_NATIVE) || k.startsWith(PREFIX_WEB)) && v is Long) {
                if (nowMs - v > PRUNE_AGE_MS) editor.remove(k)
            }
        }
    }

    private val MISSED_AT_RE = Regex("^Missed at (\\d\\d:\\d\\d)")
}
