// HAND-OWNED (quick-log). Not generated by Bubblewrap.
package io.github.palo007.twa.quicklog

import android.app.AlarmManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.os.Build
import android.util.Log
import androidx.core.app.NotificationManagerCompat
import org.json.JSONArray
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.TimeZone

/**
 * Owns the alarms for /inbox-meta/reminders.json items (plan todo 16). `rearm` is the single
 * entry point: called after a sync, on boot, and on TIME_SET/TIMEZONE_CHANGED.
 */
object ReminderScheduler {
    const val ACTION_FIRE = "io.github.palo007.twa.quicklog.ACTION_REMINDER_FIRE"
    const val EXTRA_KEY = "key"

    private const val KEY_ARMED_KEYS = "reminder_armed_keys" // JSON array of item keys
    private const val KEY_LAST_FIRED_SLOT_PREFIX = "reminder_last_fired_" // + key -> slot ms
    private const val TAG = "QuestaReminder"

    @Synchronized
    fun rearm(ctx: Context) {
        val app = ctx.applicationContext
        val p = DropboxAuth.prefs(app)
        val text = p.getString(ReminderSyncWorker.KEY_REMINDERS_JSON, null)
        val items = text?.let { parseReminderList(it) } ?: emptyList()
        val now = System.currentTimeMillis()
        val tz = TimeZone.getDefault()

        val armedBefore = readArmedKeys(p)
        val desiredKeys = items.map { it.key }.toSet()

        // Cancel alarms for keys no longer present.
        val am = alarmManager(app)
        for (staleKey in armedBefore - desiredKeys) {
            am.cancel(pendingIntent(app, staleKey))
        }

        val armedAfter = HashSet<String>()
        for (item in items) {
            val fireAt = nextFireMs(item, now, tz)
            if (fireAt == null) {
                am.cancel(pendingIntent(app, item.key))
                continue
            }
            scheduleAlarm(app, am, item, fireAt)
            armedAfter.add(item.key)
        }
        writeArmedKeys(p, armedAfter)
        Log.i(TAG, "rearm items=${items.size} armed=${armedAfter.size}")
    }

    private fun scheduleAlarm(ctx: Context, am: AlarmManager, item: ReminderItem, fireAt: Long) {
        val pi = pendingIntent(ctx, item.key, item)
        val exact = Build.VERSION.SDK_INT < 31 || am.canScheduleExactAlarms()
        try {
            when {
                Build.VERSION.SDK_INT >= 31 && am.canScheduleExactAlarms() ->
                    am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, fireAt, pi)
                Build.VERSION.SDK_INT >= 31 ->
                    am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, fireAt, pi)
                // API 23-30: exact alarms need no permission.
                Build.VERSION.SDK_INT >= 23 ->
                    am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, fireAt, pi)
                else ->
                    am.setExact(AlarmManager.RTC_WAKEUP, fireAt, pi)
            }
            Log.i(TAG, "armed key=${item.key} -> ${formatLocal(fireAt)} ${if (exact) "exact" else "inexact"}")
        } catch (t: SecurityException) {
            // Exact alarm permission revoked mid-flight: fall back to inexact.
            Log.w(TAG, "exact alarm denied for ${item.key}, using inexact", t)
            am.set(AlarmManager.RTC_WAKEUP, fireAt, pi)
            Log.i(TAG, "armed key=${item.key} -> ${formatLocal(fireAt)} inexact")
        }
    }

    private fun formatLocal(ms: Long): String =
        SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.US).format(Date(ms))

    /** Called by the receiver right after it fires: re-arm just that one item's next slot. */
    fun rearmOne(ctx: Context, key: String) {
        // Cheapest correct option: re-derive from the same stored JSON, same as a full rearm,
        // but only touch this key's alarm to avoid perturbing others mid-batch.
        val app = ctx.applicationContext
        val p = DropboxAuth.prefs(app)
        val text = p.getString(ReminderSyncWorker.KEY_REMINDERS_JSON, null) ?: return
        val item = parseReminderList(text)?.firstOrNull { it.key == key } ?: return
        val now = System.currentTimeMillis()
        val fireAt = nextFireMs(item, now, TimeZone.getDefault())
        val am = alarmManager(app)
        if (fireAt == null) {
            am.cancel(pendingIntent(app, key))
            val armed = readArmedKeys(p).toMutableSet()
            armed.remove(key)
            writeArmedKeys(p, armed)
        } else {
            scheduleAlarm(app, am, item, fireAt)
        }
    }

    fun hasExactAlarmPermission(ctx: Context): Boolean =
        Build.VERSION.SDK_INT < 31 || alarmManager(ctx).canScheduleExactAlarms()

    /**
     * True when native alarms can plausibly fire: Dropbox connected, a parsed reminder list is
     * stored, and notifications are enabled. Exact-alarm permission is NOT required here (an
     * inexact alarm still fires, just less precisely). Used by LauncherActivity to decide whether
     * the web app may go silent (`nr=1`) without leaving the user with no reminder at all.
     */
    @JvmStatic
    fun nativeReady(ctx: Context): Boolean {
        return try {
            if (!DropboxAuth.isConnected(ctx)) return false
            val text = DropboxAuth.prefs(ctx).getString(ReminderSyncWorker.KEY_REMINDERS_JSON, null)
                ?: return false
            if (parseReminderList(text) == null) return false
            NotificationManagerCompat.from(ctx).areNotificationsEnabled()
        } catch (t: Throwable) {
            false
        }
    }

    fun lastFiredSlot(ctx: Context, key: String): Long =
        DropboxAuth.prefs(ctx).getLong(KEY_LAST_FIRED_SLOT_PREFIX + key, 0L)

    fun markFiredSlot(ctx: Context, key: String, slotMs: Long) {
        DropboxAuth.prefs(ctx).edit().putLong(KEY_LAST_FIRED_SLOT_PREFIX + key, slotMs).apply()
    }

    fun armedCount(ctx: Context): Int = readArmedKeys(DropboxAuth.prefs(ctx)).size

    private fun alarmManager(ctx: Context): AlarmManager =
        ctx.getSystemService(Context.ALARM_SERVICE) as AlarmManager

    private fun pendingIntent(ctx: Context, key: String, item: ReminderItem? = null): PendingIntent {
        val intent = Intent(ACTION_FIRE).setClass(ctx, ReminderReceiver::class.java)
            .putExtra(EXTRA_KEY, key)
        val flags = PendingIntent.FLAG_UPDATE_CURRENT or
            (if (Build.VERSION.SDK_INT >= 23) PendingIntent.FLAG_IMMUTABLE else 0)
        return PendingIntent.getBroadcast(ctx, requestCode(key), intent, flags)
    }

    /** Stable, non-zero-colliding-enough request code from the key (32-bit hash is fine here). */
    private fun requestCode(key: String): Int = key.hashCode()

    private fun readArmedKeys(p: android.content.SharedPreferences): Set<String> {
        val s = p.getString(KEY_ARMED_KEYS, null) ?: return emptySet()
        return try {
            val arr = JSONArray(s)
            (0 until arr.length()).mapNotNull { arr.optString(it, null) }.toSet()
        } catch (e: Exception) {
            emptySet()
        }
    }

    private fun writeArmedKeys(p: android.content.SharedPreferences, keys: Set<String>) {
        p.edit().putString(KEY_ARMED_KEYS, JSONArray(keys.toList()).toString()).apply()
    }
}
