// HAND-OWNED (quick-log). Not generated by Bubblewrap.
package io.github.palo007.twa.quicklog

import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.util.Log

/**
 * Exported, but only reacts to system-broadcast actions (plan todo 16): device boot, wall-clock
 * time changed, timezone changed, or this app package replaced (e.g. after an update wiped
 * in-flight alarms). Re-arms every reminder from the last-known-good JSON; does not need
 * network since ReminderScheduler.rearm reads from prefs.
 */
class ReminderBootReceiver : BroadcastReceiver() {
    override fun onReceive(context: Context, intent: Intent) {
        when (intent.action) {
            Intent.ACTION_BOOT_COMPLETED,
            Intent.ACTION_TIME_CHANGED,
            Intent.ACTION_TIMEZONE_CHANGED,
            Intent.ACTION_MY_PACKAGE_REPLACED -> {
                try {
                    ReminderScheduler.rearm(context.applicationContext)
                } catch (t: Throwable) {
                    Log.w("QuestaQuickLog", "rearm on ${intent.action} failed", t)
                }
            }
        }
    }
}
