// HAND-OWNED (quick-log). Not generated by Bubblewrap.
package io.github.palo007.twa.quicklog

import org.json.JSONArray
import org.json.JSONObject
import java.util.Calendar
import java.util.TimeZone

/**
 * Contract: /inbox-meta/reminders.json, written by the PWA (plan todo 15). Do not change shape.
 * {"v":1,"updatedAt":<ms>,"items":[
 *   {"key":"<taskId>#<n>","taskId":"<id>","type":"habit|daily|todo",
 *    "title":"...","body":"...","time":"HH:MM",
 *    "date":"YYYY-MM-DD" or null, "days":[7 booleans, 0=Sunday] or null}]}
 */
data class ReminderItem(
    val key: String,
    val taskId: String,
    val type: String,
    val title: String,
    val body: String,
    val hour: Int,
    val minute: Int,
    val date: String?, // "YYYY-MM-DD" or null
    val days: List<Boolean>? // size 7, index 0 = Sunday, or null = every day
)

/** Returns null unless v==1, so a bad file never wipes existing alarms (HabitList.kt style). */
fun parseReminderList(text: String): List<ReminderItem>? {
    val o = try { JSONObject(text) } catch (e: Exception) { return null }
    if (o.optInt("v", 0) != 1) return null
    val arr = o.optJSONArray("items") ?: return null
    val out = ArrayList<ReminderItem>(arr.length())
    for (i in 0 until arr.length()) {
        val it = arr.optJSONObject(i) ?: continue
        val key = it.optString("key", "")
        val taskId = it.optString("taskId", "")
        val time = it.optString("time", "")
        val hm = parseTime(time) ?: continue
        if (key.isEmpty() || taskId.isEmpty()) continue
        val date = (it.opt("date") as? String)?.takeIf { d -> d.isNotBlank() }
        val days = parseDays(it.optJSONArray("days"))
        out.add(
            ReminderItem(
                key = key,
                taskId = taskId,
                type = it.optString("type", ""),
                title = it.optString("title", "").ifEmpty { taskId },
                body = it.optString("body", ""),
                hour = hm.first,
                minute = hm.second,
                date = date,
                days = days
            )
        )
    }
    return out
}

private fun parseTime(s: String): Pair<Int, Int>? {
    val parts = s.split(":")
    if (parts.size != 2) return null
    val h = parts[0].toIntOrNull() ?: return null
    val m = parts[1].toIntOrNull() ?: return null
    if (h !in 0..23 || m !in 0..59) return null
    return h to m
}

private fun parseDays(arr: JSONArray?): List<Boolean>? {
    if (arr == null) return null
    if (arr.length() != 7) return null
    val out = ArrayList<Boolean>(7)
    for (i in 0 until 7) out.add(arr.optBoolean(i, false))
    return out
}

/**
 * Next fire time strictly after [nowMs], phone-local wall clock in [tz]. A one-shot with a
 * [ReminderItem.date] in the past (relative to now) returns null so we do not schedule it.
 * `days` null means every day; otherwise only days where the flag is true (index 0 = Sunday).
 */
fun nextFireMs(item: ReminderItem, nowMs: Long, tz: TimeZone): Long? {
    val cal = Calendar.getInstance(tz)
    cal.timeInMillis = nowMs

    if (item.date != null) {
        val parts = item.date.split("-")
        if (parts.size != 3) return null
        val y = parts[0].toIntOrNull() ?: return null
        val mo = parts[1].toIntOrNull() ?: return null
        val d = parts[2].toIntOrNull() ?: return null
        cal.set(Calendar.YEAR, y)
        cal.set(Calendar.MONTH, mo - 1)
        cal.set(Calendar.DAY_OF_MONTH, d)
        cal.set(Calendar.HOUR_OF_DAY, item.hour)
        cal.set(Calendar.MINUTE, item.minute)
        cal.set(Calendar.SECOND, 0)
        cal.set(Calendar.MILLISECOND, 0)
        return if (cal.timeInMillis > nowMs) cal.timeInMillis else null
    }

    // Recurring: scan today .. today+7 for the first allowed day whose slot is strictly after now.
    for (offset in 0..7) {
        val c = Calendar.getInstance(tz)
        c.timeInMillis = nowMs
        c.add(Calendar.DAY_OF_YEAR, offset)
        c.set(Calendar.HOUR_OF_DAY, item.hour)
        c.set(Calendar.MINUTE, item.minute)
        c.set(Calendar.SECOND, 0)
        c.set(Calendar.MILLISECOND, 0)
        if (c.timeInMillis <= nowMs) continue
        val dow = c.get(Calendar.DAY_OF_WEEK) - Calendar.SUNDAY // 0 = Sunday
        if (item.days == null || item.days.getOrElse(dow) { false }) return c.timeInMillis
    }
    return null // days == 7 falses: never fires
}
