// HAND-OWNED (quick-log). Not generated by Bubblewrap.
package io.github.palo007.twa.quicklog

import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.os.Build
import android.util.Log
import androidx.core.app.NotificationCompat
import androidx.core.app.NotificationManagerCompat
import java.util.TimeZone

/**
 * Fires one reminder alarm (plan todo 16). Not exported: only our own PendingIntents from
 * ReminderScheduler start it. Re-reads reminders.json by key at fire time so the title/body
 * shown are current even if the alarm was armed with an older sync.
 */
class ReminderReceiver : BroadcastReceiver() {
    override fun onReceive(context: Context, intent: Intent) {
        if (intent.action != ReminderScheduler.ACTION_FIRE) return
        val key = intent.getStringExtra(ReminderScheduler.EXTRA_KEY) ?: return
        val ctx = context.applicationContext

        val text = DropboxAuth.prefs(ctx).getString(ReminderSyncWorker.KEY_REMINDERS_JSON, null)
        val item = text?.let { parseReminderList(it) }?.firstOrNull { it.key == key }

        if (item != null) {
            val now = System.currentTimeMillis()
            // The slot this alarm was meant for: same wall-clock minute, computed from now
            // rounded down would be fragile across DST; instead guard with a coarse window
            // using the last fired timestamp itself (see below).
            val last = ReminderScheduler.lastFiredSlot(ctx, key)
            // Guard against a double fire of the same slot (e.g. duplicate broadcast delivery):
            // skip only if we already fired within the last 60s for this key.
            if (now - last > 60_000L) {
                // The intended slot for this alarm: item's time on TODAY's date, even if the
                // alarm actually fired late (e.g. inexact window delay).
                val today = ReminderDedupe.localDateString(now, TimeZone.getDefault())
                val slot = ReminderDedupe.buildSlotKey(
                    item.title, today, ReminderDedupe.timeString(item.hour, item.minute)
                )
                // The web app (via DelegationService) may have already shown this exact slot:
                // skip our own copy but still mark the alarm's slot fired so it does not re-post
                // a moment later on the next check.
                if (!ReminderDedupe.webShown(ctx, slot)) {
                    postNotification(ctx, item)
                    ReminderDedupe.markNative(ctx, slot, now)
                    Log.i(TAG, "fire key=$key slot=$slot posted")
                } else {
                    Log.i(TAG, "fire key=$key slot=$slot skipped reason=webShown")
                }
                ReminderScheduler.markFiredSlot(ctx, key, now)
            }
        }

        // Always re-arm this key's next slot, even if the item vanished (rearmOne cancels it).
        ReminderScheduler.rearmOne(ctx, key)
    }

    private fun postNotification(ctx: Context, item: ReminderItem) {
        if (Build.VERSION.SDK_INT >= 33) {
            val granted = ctx.checkSelfPermission(android.Manifest.permission.POST_NOTIFICATIONS) ==
                PackageManager.PERMISSION_GRANTED
            if (!granted) return
        }
        ensureChannel(ctx)

        val launch = ctx.packageManager.getLaunchIntentForPackage(ctx.packageName)
        val contentPi = if (launch != null) {
            val flags = PendingIntent.FLAG_UPDATE_CURRENT or
                (if (Build.VERSION.SDK_INT >= 23) PendingIntent.FLAG_IMMUTABLE else 0)
            PendingIntent.getActivity(ctx, item.key.hashCode(), launch, flags)
        } else null

        val notification = NotificationCompat.Builder(ctx, CHANNEL_ID)
            .setSmallIcon(io.github.palo007.twa.R.drawable.ic_notification_icon)
            .setContentTitle(item.title)
            .setContentText(item.body.ifEmpty { null })
            .setAutoCancel(true)
            .setContentIntent(contentPi)
            .setPriority(NotificationCompat.PRIORITY_DEFAULT)
            .build()

        try {
            NotificationManagerCompat.from(ctx).notify(item.key.hashCode(), notification)
        } catch (e: SecurityException) {
            // Permission revoked between the check above and here: skip silently.
        }
    }

    private fun ensureChannel(ctx: Context) {
        if (Build.VERSION.SDK_INT < 26) return
        val nm = ctx.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
        if (nm.getNotificationChannel(CHANNEL_ID) != null) return
        nm.createNotificationChannel(
            NotificationChannel(CHANNEL_ID, "Reminders", NotificationManager.IMPORTANCE_DEFAULT)
        )
    }

    companion object {
        const val CHANNEL_ID = "reminders"
        private const val TAG = "QuestaReminder"
    }
}
