// HAND-OWNED (quick-log). Not generated by Bubblewrap.
package io.github.palo007.twa.quicklog

import android.content.Context
import android.util.Log
import androidx.work.BackoffPolicy
import androidx.work.Constraints
import androidx.work.ExistingPeriodicWorkPolicy
import androidx.work.ExistingWorkPolicy
import androidx.work.NetworkType
import androidx.work.OneTimeWorkRequest
import androidx.work.PeriodicWorkRequest
import androidx.work.WorkManager
import androidx.work.Worker
import androidx.work.WorkerParameters
import com.dropbox.core.DbxException
import com.dropbox.core.InvalidAccessTokenException
import com.dropbox.core.v2.files.DownloadErrorException
import java.io.ByteArrayOutputStream
import java.io.IOException
import java.util.concurrent.TimeUnit

/**
 * Downloads /inbox-meta/reminders.json (plan todo 16), keeps the last good JSON in prefs, then
 * re-arms all alarms. Mirrors ShortcutRefreshWorker's download/error pattern.
 */
class ReminderSyncWorker(ctx: Context, params: WorkerParameters) : Worker(ctx, params) {

    override fun doWork(): Result {
        val ctx = applicationContext
        val client = DropboxAuth.client(ctx)
        if (client == null) {
            // Not connected: nothing to fetch, but still re-arm from whatever we already have
            // (e.g. after a reboot before the user reconnects).
            Log.i(TAG, "not connected, re-arming from existing prefs")
            ReminderScheduler.rearm(ctx)
            return Result.success()
        }
        val p = DropboxAuth.prefs(ctx)
        return try {
            val out = ByteArrayOutputStream()
            client.files().download(REMINDERS_PATH).download(out)
            val text = out.toString("UTF-8")
            val parsed = parseReminderList(text)
            if (parsed == null) {
                setStatus(ctx, "Reminder list file is not readable (v1 expected).")
                Log.i(TAG, "downloaded but unreadable (v1 expected)")
            } else {
                p.edit().putString(KEY_REMINDERS_JSON, text).apply()
                setStatus(ctx, null)
                Log.i(TAG, "downloaded ok items=${parsed.size}")
            }
            ReminderScheduler.rearm(ctx)
            Result.success()
        } catch (e: DownloadErrorException) {
            if (e.errorValue.isPath && e.errorValue.pathValue.isNotFound) {
                // The PWA writes it after its first good sync on a new build. Keep existing alarms.
                setStatus(ctx, "No reminder list yet. Open Questa once and let it sync.")
                Log.i(TAG, "not found on Dropbox yet")
                ReminderScheduler.rearm(ctx)
                Result.success()
            } else {
                Log.i(TAG, "download error, retrying", e)
                Result.retry()
            }
        } catch (e: InvalidAccessTokenException) {
            Log.i(TAG, "auth broken, re-arming from existing prefs", e)
            DropboxAuth.markAuthBroken(ctx)
            ReminderScheduler.rearm(ctx)
            Result.failure()
        } catch (e: DbxException) {
            Log.i(TAG, "Dropbox error, retrying", e)
            Result.retry()
        } catch (e: IOException) {
            Log.i(TAG, "IO error, retrying", e)
            Result.retry()
        }
    }

    companion object {
        const val REMINDERS_PATH = "/inbox-meta/reminders.json"
        const val KEY_REMINDERS_JSON = "reminders_json"
        const val KEY_LAST_REFRESH = "reminders_refresh_ms"
        const val KEY_STATUS = "reminders_status"
        private const val TAG = "QuestaReminder"
        private const val WORK_NOW = "questa-reminder-sync"
        private const val WORK_PERIODIC = "questa-reminder-sync-periodic"

        private fun setStatus(ctx: Context, msg: String?) {
            DropboxAuth.prefs(ctx).edit()
                .putLong(KEY_LAST_REFRESH, System.currentTimeMillis())
                .putString(KEY_STATUS, msg)
                .apply()
        }

        private fun net() = Constraints.Builder().setRequiredNetworkType(NetworkType.CONNECTED).build()

        @JvmStatic
        fun enqueueNow(ctx: Context) {
            val req = OneTimeWorkRequest.Builder(ReminderSyncWorker::class.java)
                .setConstraints(net())
                .setBackoffCriteria(BackoffPolicy.EXPONENTIAL, 30, TimeUnit.SECONDS)
                .build()
            WorkManager.getInstance(ctx.applicationContext)
                .enqueueUniqueWork(WORK_NOW, ExistingWorkPolicy.REPLACE, req)
        }

        /**
         * Every 15 min, the WorkManager minimum (plan todo 16, tightened so a missed reminder is
         * caught quickly). UPDATE (WorkManager 2.10.5) so existing installs pick up the new
         * interval instead of keeping their old 1 h periodic work forever.
         */
        fun ensurePeriodic(ctx: Context) {
            val req = PeriodicWorkRequest.Builder(ReminderSyncWorker::class.java, 15, TimeUnit.MINUTES)
                .setConstraints(net())
                .build()
            WorkManager.getInstance(ctx.applicationContext)
                .enqueueUniquePeriodicWork(WORK_PERIODIC, ExistingPeriodicWorkPolicy.UPDATE, req)
        }
    }
}
