// HAND-OWNED (quick-log). Not generated by Bubblewrap.
package io.github.palo007.twa.quicklog

import android.Manifest
import android.app.Activity
import android.content.Intent
import android.content.pm.PackageManager
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.provider.Settings
import android.text.format.DateUtils
import android.view.ViewGroup
import android.widget.Button
import android.widget.LinearLayout
import android.widget.ScrollView
import android.widget.TextView
import androidx.core.app.ActivityCompat

/**
 * Minimal quick-log settings (plan todo 8): connect / disconnect Dropbox, status,
 * refresh habits. Reached from the "Connect Dropbox" long-press item while not
 * connected, and from Android Settings > Apps > Questa (APPLICATION_PREFERENCES).
 */
class SettingsActivity : Activity() {
    private lateinit var status: TextView
    private lateinit var connect: Button
    private lateinit var refresh: Button
    private lateinit var remindersStatus: TextView
    private lateinit var allowExactAlarms: Button
    private lateinit var allowNotifications: Button

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        title = "Questa quick log"
        val pad = (16 * resources.displayMetrics.density).toInt()
        val col = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            setPadding(pad, pad, pad, pad)
        }
        status = TextView(this).apply { textSize = 16f }
        connect = Button(this)
        refresh = Button(this).apply {
            text = "Refresh habits now"
            setOnClickListener {
                ShortcutRefreshWorker.enqueueNow(this@SettingsActivity)
                InboxUploadWorker.enqueue(this@SettingsActivity)
                status.append("\n\nRefresh started. Come back in a few seconds.")
            }
        }
        val help = TextView(this).apply {
            textSize = 14f
            text = "Tick \"Quick log\" on a habit in Questa. After Questa syncs, the first " +
                "${ShortcutPublisher.MAX_ITEMS} ticked habit items show when you long-press the Questa icon. " +
                "A tap logs +1 without opening Questa."
        }
        remindersStatus = TextView(this).apply { textSize = 16f }
        allowExactAlarms = Button(this).apply {
            text = "Allow exact alarms"
            setOnClickListener {
                if (Build.VERSION.SDK_INT >= 31) {
                    startActivity(
                        Intent(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM, Uri.parse("package:$packageName"))
                    )
                }
            }
        }
        allowNotifications = Button(this).apply {
            text = "Allow notifications"
            setOnClickListener {
                if (Build.VERSION.SDK_INT >= 33) {
                    ActivityCompat.requestPermissions(
                        this@SettingsActivity, arrayOf(Manifest.permission.POST_NOTIFICATIONS), REQ_NOTIFICATIONS
                    )
                }
            }
        }
        val lp = { LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT).apply { topMargin = pad } }
        col.addView(status, lp())
        col.addView(connect, lp())
        col.addView(refresh, lp())
        col.addView(remindersStatus, lp())
        col.addView(allowExactAlarms, lp())
        col.addView(allowNotifications, lp())
        col.addView(help, lp())
        setContentView(ScrollView(this).apply { addView(col) })
    }

    override fun onResume() {
        super.onResume()
        if (DropboxAuth.captureLoginResult(this)) {
            // Fresh login: flush the queue, fetch habits, and swap "Connect" for habit items.
            InboxUploadWorker.enqueue(this)
            ShortcutRefreshWorker.enqueueNow(this)
            ShortcutRefreshWorker.ensurePeriodic(this)
            ShortcutPublisher.publish(this)
            ReminderSyncWorker.enqueueNow(this)
            ReminderSyncWorker.ensurePeriodic(this)
        }
        // Covers returning from the "Allow exact alarms" / "Allow notifications" system screens.
        ReminderScheduler.rearm(this)
        render()
    }

    private fun render() {
        val p = DropboxAuth.prefs(this)
        val connected = DropboxAuth.isConnected(this)
        val broken = DropboxAuth.isAuthBroken(this)
        val queued = InboxStore(this).count()
        val lastUp = p.getLong(InboxUploadWorker.KEY_LAST_UPLOAD, 0)
        val lastRefresh = p.getLong(ShortcutRefreshWorker.KEY_LAST_REFRESH, 0)
        val habitStatus = p.getString(ShortcutRefreshWorker.KEY_STATUS, null)
        val sb = StringBuilder()
        sb.append(
            when {
                !connected -> "Dropbox: not connected"
                broken -> "Dropbox: login expired. Connect again."
                else -> "Dropbox: connected"
            }
        )
        sb.append("\nWaiting to upload: ").append(queued)
        sb.append("\nLast upload: ").append(ago(lastUp))
        sb.append("\nHabit list checked: ").append(ago(lastRefresh))
        if (habitStatus != null) sb.append("\n").append(habitStatus)
        status.text = sb

        if (connected && !broken) {
            connect.text = "Disconnect Dropbox"
            connect.setOnClickListener {
                DropboxAuth.disconnect(this)
                ShortcutPublisher.publish(this)
                render()
            }
        } else {
            connect.text = if (broken) "Reconnect Dropbox" else "Connect Dropbox"
            connect.setOnClickListener { DropboxAuth.startLogin(this) }
        }
        refresh.isEnabled = connected && !broken

        val armed = ReminderScheduler.armedCount(this)
        val lastReminderRefresh = p.getLong(ReminderSyncWorker.KEY_LAST_REFRESH, 0)
        val reminderStatusMsg = p.getString(ReminderSyncWorker.KEY_STATUS, null)
        val exactAllowed = ReminderScheduler.hasExactAlarmPermission(this)
        val rsb = StringBuilder()
        rsb.append("Reminders: ").append(armed).append(" scheduled")
        rsb.append("\nLast checked: ").append(ago(lastReminderRefresh))
        rsb.append("\nExact alarms: ").append(if (exactAllowed) "yes" else "no")
        if (reminderStatusMsg != null) rsb.append("\n").append(reminderStatusMsg)
        remindersStatus.text = rsb

        allowExactAlarms.visibility =
            if (Build.VERSION.SDK_INT >= 31 && !exactAllowed) android.view.View.VISIBLE else android.view.View.GONE

        val notificationsGranted = Build.VERSION.SDK_INT < 33 ||
            checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS) == PackageManager.PERMISSION_GRANTED
        allowNotifications.visibility =
            if (Build.VERSION.SDK_INT >= 33 && !notificationsGranted) android.view.View.VISIBLE else android.view.View.GONE
    }

    override fun onRequestPermissionsResult(requestCode: Int, permissions: Array<out String>, grantResults: IntArray) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults)
        if (requestCode == REQ_NOTIFICATIONS) render()
    }

    companion object {
        private const val REQ_NOTIFICATIONS = 1001
    }

    private fun ago(ms: Long): CharSequence =
        if (ms <= 0) "never"
        else DateUtils.getRelativeTimeSpanString(ms, System.currentTimeMillis(), DateUtils.MINUTE_IN_MILLIS)
}
