// HAND-OWNED (quick-log). Not generated by Bubblewrap.
package io.github.palo007.twa.quicklog

import android.content.Context
import androidx.work.BackoffPolicy
import androidx.work.Constraints
import androidx.work.ExistingPeriodicWorkPolicy
import androidx.work.ExistingWorkPolicy
import androidx.work.NetworkType
import androidx.work.OneTimeWorkRequest
import androidx.work.PeriodicWorkRequest
import androidx.work.WorkManager
import androidx.work.Worker
import androidx.work.WorkerParameters
import com.dropbox.core.DbxException
import com.dropbox.core.InvalidAccessTokenException
import com.dropbox.core.v2.files.DownloadErrorException
import java.io.ByteArrayOutputStream
import java.io.IOException
import java.util.concurrent.TimeUnit

/** Downloads /inbox-meta/habits.json and republishes the long-press habit items. */
class ShortcutRefreshWorker(ctx: Context, params: WorkerParameters) : Worker(ctx, params) {

    override fun doWork(): Result {
        val ctx = applicationContext
        val client = DropboxAuth.client(ctx)
        if (client == null) {
            ShortcutPublisher.publish(ctx)
            return Result.success()
        }
        val p = DropboxAuth.prefs(ctx)
        return try {
            val out = ByteArrayOutputStream()
            client.files().download(HABITS_PATH).download(out)
            val text = out.toString("UTF-8")
            if (parseHabitList(text) == null) {
                setStatus(ctx, "Habit list file is not readable (v1 expected).")
            } else {
                p.edit().putString(ShortcutPublisher.KEY_HABITS_JSON, text).apply()
                setStatus(ctx, null)
            }
            ShortcutPublisher.publish(ctx)
            Result.success()
        } catch (e: DownloadErrorException) {
            if (e.errorValue.isPath && e.errorValue.pathValue.isNotFound) {
                // The PWA writes it after its first good sync on a new build.
                setStatus(ctx, "No habit list in Dropbox yet. Open Questa once and let it sync.")
                ShortcutPublisher.publish(ctx)
                Result.success()
            } else {
                Result.retry()
            }
        } catch (e: InvalidAccessTokenException) {
            DropboxAuth.markAuthBroken(ctx)
            ShortcutPublisher.publish(ctx)
            Result.failure()
        } catch (e: DbxException) {
            Result.retry()
        } catch (e: IOException) {
            Result.retry()
        }
    }

    companion object {
        const val HABITS_PATH = "/inbox-meta/habits.json"
        const val KEY_LAST_REFRESH = "habits_refresh_ms"
        const val KEY_STATUS = "habits_status"
        private const val WORK_NOW = "questa-shortcut-refresh"
        private const val WORK_PERIODIC = "questa-shortcut-refresh-periodic"

        private fun setStatus(ctx: Context, msg: String?) {
            DropboxAuth.prefs(ctx).edit()
                .putLong(KEY_LAST_REFRESH, System.currentTimeMillis())
                .putString(KEY_STATUS, msg)
                .apply()
        }

        private fun net() = Constraints.Builder().setRequiredNetworkType(NetworkType.CONNECTED).build()

        fun enqueueNow(ctx: Context) {
            val req = OneTimeWorkRequest.Builder(ShortcutRefreshWorker::class.java)
                .setConstraints(net())
                .setBackoffCriteria(BackoffPolicy.EXPONENTIAL, 30, TimeUnit.SECONDS)
                .build()
            WorkManager.getInstance(ctx.applicationContext)
                .enqueueUniqueWork(WORK_NOW, ExistingWorkPolicy.REPLACE, req)
        }

        /** Every 6 h (plan todo 12). KEEP: calling it again does not reset the timer. */
        fun ensurePeriodic(ctx: Context) {
            val req = PeriodicWorkRequest.Builder(ShortcutRefreshWorker::class.java, 6, TimeUnit.HOURS)
                .setConstraints(net())
                .build()
            WorkManager.getInstance(ctx.applicationContext)
                .enqueueUniquePeriodicWork(WORK_PERIODIC, ExistingPeriodicWorkPolicy.KEEP, req)
        }
    }
}
