// HAND-OWNED (quick-log). Not generated by Bubblewrap.
package io.github.palo007.twa.quicklog

import android.content.Context
import android.content.Intent
import androidx.core.content.pm.ShortcutInfoCompat
import androidx.core.content.pm.ShortcutManagerCompat
import androidx.core.graphics.drawable.IconCompat
import io.github.palo007.twa.R

/**
 * Owns only the dynamic shortcuts whose id starts with "ql-". Others (the TWA's
 * "Site settings" item) are never touched. The launcher shows about 4-5 items in
 * total: "Site settings" + up to [MAX_ITEMS] habit items (no static items since 2026-09-24).
 */
object ShortcutPublisher {
    const val KEY_HABITS_JSON = "habits_json"
    private const val KEY_SIGNATURE = "shortcut_sig"
    private const val PREFIX = "ql-"
    private const val CONNECT_ID = "ql-connect"
    const val MAX_ITEMS = 3

    @Synchronized
    fun publish(ctx: Context) {
        val app = ctx.applicationContext
        val p = DropboxAuth.prefs(app)
        val connected = DropboxAuth.isConnected(app)
        val broken = connected && DropboxAuth.isAuthBroken(app)
        val all: List<Habit>? = p.getString(KEY_HABITS_JSON, null)?.let { parseHabitList(it) }

        // Not connected: only "Connect Dropbox". Login expired: "Reconnect Dropbox" plus
        // fewer habits, so taps keep queueing safely until the user reconnects.
        val desired: List<ShortcutInfoCompat> = when {
            !connected -> listOf(connectShortcut(app, false))
            else -> {
                val items = pickShortcutItems(all ?: emptyList(), if (broken) MAX_ITEMS - 1 else MAX_ITEMS)
                    .mapIndexed { i, item -> habitShortcut(app, item, i + if (broken) 1 else 0) }
                if (broken) listOf(connectShortcut(app, true)) + items else items
            }
        }

        val ours = ShortcutManagerCompat.getDynamicShortcuts(app).map { it.id }.filter { it.startsWith(PREFIX) }
        val sig = desired.joinToString("|") { it.id + "=" + it.shortLabel }
        // Launchers rate-limit background updates; skip when nothing changed.
        if (sig == p.getString(KEY_SIGNATURE, null) && ours.toSet() == desired.map { it.id }.toSet()) return

        val stale = ours - desired.map { it.id }.toSet()
        if (stale.isNotEmpty()) ShortcutManagerCompat.removeDynamicShortcuts(app, stale)
        if (desired.isNotEmpty() && !ShortcutManagerCompat.addDynamicShortcuts(app, desired)) return

        // A habit pinned to the home screen but deleted in Questa: grey it out instead of
        // letting it log to an id the PWA would reject.
        if (connected && !broken && all != null) {
            val known = all.flatMap { listOf(PREFIX + "h-" + it.id, PREFIX + "h-" + it.id + "-down") }.toSet()
            val gone = ShortcutManagerCompat.getShortcuts(app, ShortcutManagerCompat.FLAG_MATCH_PINNED)
                .map { it.id }
                .filter { it.startsWith(PREFIX + "h-") && it !in known }
            if (gone.isNotEmpty()) ShortcutManagerCompat.disableShortcuts(app, gone, "Habit no longer in Questa")
        }
        p.edit().putString(KEY_SIGNATURE, sig).apply()
    }

    private fun icon(ctx: Context) = IconCompat.createWithResource(ctx, R.drawable.shortcut_0)

    private fun habitShortcut(ctx: Context, item: ShortcutItem, rank: Int): ShortcutInfoCompat {
        val h = item.habit
        val dir = item.dir
        val id = if (dir == -1) PREFIX + "h-" + h.id + "-down" else PREFIX + "h-" + h.id
        val label = if (dir == -1) "−" + "1 " + h.title else "+1 " + h.title
        val intent = Intent(QuickLogActivity.ACTION)
            .setClass(ctx, QuickLogActivity::class.java)
            .putExtra(QuickLogActivity.EXTRA_HABIT_ID, h.id)
            .putExtra(QuickLogActivity.EXTRA_TITLE, h.title)
            .putExtra(QuickLogActivity.EXTRA_DIR, dir)
        return ShortcutInfoCompat.Builder(ctx, id)
            .setShortLabel(label.take(25))
            .setLongLabel(label.take(25))
            .setIcon(icon(ctx))
            .setIntent(intent)
            .setRank(rank)
            .build()
    }

    private fun connectShortcut(ctx: Context, reconnect: Boolean): ShortcutInfoCompat {
        val label = if (reconnect) "Reconnect Dropbox" else "Connect Dropbox"
        return ShortcutInfoCompat.Builder(ctx, CONNECT_ID)
            .setShortLabel(label)
            .setLongLabel("$label for quick log")
            .setIcon(icon(ctx))
            .setIntent(Intent(Intent.ACTION_VIEW).setClass(ctx, SettingsActivity::class.java))
            .setRank(0)
            .build()
    }
}
